/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1ApplicationStatisticsResponse struct {
	EnvCount int64 `json:"envCount"`
	RevisionCount int64 `json:"revisionCount"`
	TargetCount int64 `json:"targetCount"`
	WorkflowCount int64 `json:"workflowCount"`
}
