/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1AppCompareReq struct {
	CompareLatestWithRunning *V1CompareLatestWithRunningOption `json:"compareLatestWithRunning,omitempty"`
	CompareRevisionWithLatest *V1CompareRevisionWithLatestOption `json:"compareRevisionWithLatest,omitempty"`
	CompareRevisionWithRunning *V1CompareRevisionWithRunningOption `json:"compareRevisionWithRunning,omitempty"`
}
