/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1AddonDefinition struct {
	Description string `json:"description,omitempty"`
	Name string `json:"name,omitempty"`
	Type_ string `json:"type,omitempty"`
}
