/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1CreateClusterRequest struct {
	Alias string `json:"alias,omitempty"`
	DashboardURL string `json:"dashboardURL,omitempty"`
	Description string `json:"description,omitempty"`
	Icon string `json:"icon"`
	KubeConfig string `json:"kubeConfig,omitempty"`
	KubeConfigSecret string `json:"kubeConfigSecret,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	Name string `json:"name"`
}
