/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1ClusterResourceInfo struct {
	CpuCapacity int64 `json:"cpuCapacity"`
	CpuUsed int64 `json:"cpuUsed"`
	GpuCapacity int64 `json:"gpuCapacity,omitempty"`
	GpuUsed int64 `json:"gpuUsed,omitempty"`
	MasterNumber int32 `json:"masterNumber"`
	MemoryCapacity int64 `json:"memoryCapacity"`
	MemoryUsed int64 `json:"memoryUsed"`
	PodCapacity int64 `json:"podCapacity"`
	PodUsed int64 `json:"podUsed"`
	StorageClassList []string `json:"storageClassList,omitempty"`
	WorkerNumber int32 `json:"workerNumber"`
}
