/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ConditionCondition struct {
	LastTransitionTime string `json:"lastTransitionTime"`
	Message string `json:"message,omitempty"`
	Reason string `json:"reason"`
	Status string `json:"status"`
	Type_ string `json:"type"`
}
