/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TypesKubernetesService struct {
	Name string `json:"name"`
	Namespace string `json:"namespace"`
	Port int32 `json:"port"`
}
