/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1CreateApplicationTriggerRequest struct {
	Alias string `json:"alias,omitempty"`
	ComponentName string `json:"componentName,omitempty"`
	Description string `json:"description,omitempty"`
	Name string `json:"name"`
	PayloadType string `json:"payloadType"`
	Registry string `json:"registry,omitempty"`
	Type_ string `json:"type"`
	WorkflowName string `json:"workflowName"`
}
