/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CommonTerraform struct {
	Configuration string `json:"configuration"`
	CustomRegion string `json:"customRegion,omitempty"`
	DeleteResource bool `json:"deleteResource,omitempty"`
	GitCredentialsSecretReference *V1SecretReference `json:"gitCredentialsSecretReference,omitempty"`
	Path string `json:"path,omitempty"`
	ProviderRef *TypesReference `json:"providerRef,omitempty"`
	Type_ string `json:"type,omitempty"`
	WriteConnectionSecretToRef *TypesSecretReference `json:"writeConnectionSecretToRef,omitempty"`
}
