/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type V1DetailClusterResponse struct {
	Alias string `json:"alias"`
	ApiServerURL string `json:"apiServerURL"`
	CreateTime time.Time `json:"createTime"`
	DashboardURL string `json:"dashboardURL"`
	Description string `json:"description"`
	Icon string `json:"icon"`
	KubeConfig string `json:"kubeConfig"`
	KubeConfigSecret string `json:"kubeConfigSecret"`
	Labels map[string]string `json:"labels"`
	Name string `json:"name"`
	Provider *ModelProviderInfo `json:"provider"`
	Reason string `json:"reason"`
	ResourceInfo *V1ClusterResourceInfo `json:"resourceInfo"`
	Status string `json:"status"`
	UpdateTime time.Time `json:"updateTime"`
}
