/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1beta1PolicyDefinitionSpec struct {
	DefinitionRef *CommonDefinitionReference `json:"definitionRef,omitempty"`
	ManageHealthCheck bool `json:"manageHealthCheck,omitempty"`
	Schematic *CommonSchematic `json:"schematic,omitempty"`
}
