/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1GetPipelineRunLogResponse struct {
	Id string `json:"id"`
	Log string `json:"log"`
	Name string `json:"name"`
	Phase string `json:"phase"`
	Source string `json:"source"`
	Type_ string `json:"type"`
}
