/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type V1PermissionBase struct {
	Actions []string `json:"actions"`
	Alias string `json:"alias"`
	CreateTime time.Time `json:"createTime"`
	Effect string `json:"effect"`
	Name string `json:"name"`
	Resources []string `json:"resources"`
	UpdateTime time.Time `json:"updateTime"`
}
