/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ConfigDistribution struct {
	Application *TypesNamespacedName `json:"application"`
	Configs []ConfigNamespacedName `json:"configs"`
	CreatedTime time.Time `json:"createdTime"`
	Name string `json:"name"`
	Namespace string `json:"namespace"`
	Status *CommonAppStatus `json:"status"`
	Targets []ConfigClusterTarget `json:"targets"`
}
