/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1CreateConfigRequest struct {
	Alias string `json:"alias"`
	Description string `json:"description"`
	Name string `json:"name"`
	Properties string `json:"properties,omitempty"`
	Template *V1NamespacedName `json:"template"`
}
