/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CommonPolicyStatus struct {
	Name string `json:"name"`
	Status string `json:"status,omitempty"`
	Type_ string `json:"type"`
}
