/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1ListClusterResponse struct {
	Clusters []V1ClusterBase `json:"clusters"`
	Total int64 `json:"total"`
}
