/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1RunStat struct {
	ActiveNum int32 `json:"activeNum"`
	Total *V1RunStatInfo `json:"total"`
	Week []V1RunStatInfo `json:"week"`
}
