/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type V1DetailPolicyResponse struct {
	Alias string `json:"alias"`
	CreateTime time.Time `json:"createTime"`
	Creator string `json:"creator"`
	Description string `json:"description"`
	EnvName string `json:"envName"`
	Name string `json:"name"`
	Properties *ModelJsonStruct `json:"properties"`
	Type_ string `json:"type"`
	UpdateTime time.Time `json:"updateTime"`
	WorkflowPolicyBind []V1WorkflowPolicyBinding `json:"workflowPolicyBind,omitempty"`
}
