/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CommonApplicationComponentStatus struct {
	Cluster string `json:"cluster,omitempty"`
	Env string `json:"env,omitempty"`
	Healthy bool `json:"healthy"`
	Message string `json:"message,omitempty"`
	Name string `json:"name"`
	Namespace string `json:"namespace,omitempty"`
	Scopes []V1ObjectReference `json:"scopes,omitempty"`
	Traits []CommonApplicationTraitStatus `json:"traits,omitempty"`
	WorkloadDefinition *CommonWorkloadGvk `json:"workloadDefinition,omitempty"`
}
