/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1UpdateWorkflowRequest struct {
	Alias string `json:"alias,omitempty"`
	Default_ bool `json:"default"`
	Description string `json:"description,omitempty"`
	Mode string `json:"mode"`
	Steps []V1WorkflowStep `json:"steps,omitempty"`
	SubMode string `json:"subMode"`
}
