/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1UpdateAddonRegistryRequest struct {
	Git *AddonGitAddonSource `json:"git,omitempty"`
	Gitee *AddonGiteeAddonSource `json:"gitee,omitempty"`
	Gitlab *AddonGitlabAddonSource `json:"gitlab,omitempty"`
	Helm *AddonHelmSource `json:"helm,omitempty"`
	Oss *AddonOssAddonSource `json:"oss,omitempty"`
}
