/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1InputVar struct {
	From string `json:"from"`
	FromStep string `json:"fromStep"`
	ParameterKey string `json:"parameterKey"`
	Value string `json:"value"`
}
