/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1History struct {
	Author string `json:"author,omitempty"`
	Comment string `json:"comment,omitempty"`
	Created string `json:"created,omitempty"`
	CreatedBy string `json:"created_by,omitempty"`
	EmptyLayer bool `json:"empty_layer,omitempty"`
}
