/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type V1ApplicationTemplateBase struct {
	CreateTime time.Time `json:"createTime"`
	TemplateName string `json:"templateName"`
	UpdateTime time.Time `json:"updateTime"`
	Versions []V1ApplicationTemplateVersion `json:"versions,omitempty"`
}
