/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1CreateEnvRequest struct {
	Alias               string   `json:"alias,omitempty"`
	AllowTargetConflict bool     `json:"allowTargetConflict,omitempty"`
	Description         string   `json:"description,omitempty"`
	Name                string   `json:"name"`
	Namespace           string   `json:"namespace"`
	Project             string   `json:"project"`
	Targets             []string `json:"targets,omitempty"`
}
