/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ChartMetadata struct {
	Annotations map[string]string `json:"annotations,omitempty"`
	ApiVersion string `json:"apiVersion,omitempty"`
	AppVersion string `json:"appVersion,omitempty"`
	Condition string `json:"condition,omitempty"`
	Dependencies []ChartDependency `json:"dependencies,omitempty"`
	Deprecated bool `json:"deprecated,omitempty"`
	Description string `json:"description,omitempty"`
	Home string `json:"home,omitempty"`
	Icon string `json:"icon,omitempty"`
	Keywords []string `json:"keywords,omitempty"`
	KubeVersion string `json:"kubeVersion,omitempty"`
	Maintainers []ChartMaintainer `json:"maintainers,omitempty"`
	Name string `json:"name,omitempty"`
	Sources []string `json:"sources,omitempty"`
	Tags string `json:"tags,omitempty"`
	Type_ string `json:"type,omitempty"`
	Version string `json:"version,omitempty"`
}
