/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1beta1Workflow struct {
	Mode  *V1alpha1WorkflowExecuteMode `json:"mode,omitempty"`
	Ref   string                       `json:"ref,omitempty"`
	Steps []V1alpha1WorkflowStep       `json:"steps,omitempty"`
}
