/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1CreateTargetRequest struct {
	Alias       string           `json:"alias,omitempty"`
	Cluster     *V1ClusterTarget `json:"cluster,omitempty"`
	Description string           `json:"description,omitempty"`
	Name        string           `json:"name"`
	Project     string           `json:"project"`
	Variable    *interface{}     `json:"variable,omitempty"`
}
