/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CommonApplicationTraitStatus struct {
	Healthy bool `json:"healthy"`
	Message string `json:"message,omitempty"`
	Type_ string `json:"type"`
}
