/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1RunStatInfo struct {
	Fail    int32 `json:"fail"`
	Success int32 `json:"success"`
	Total   int32 `json:"total"`
}
