/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SchemaValidate struct {
	DefaultValue *SchemaValidateDefaultValue `json:"defaultValue,omitempty"`
	Immutable bool `json:"immutable"`
	Max float64 `json:"max,omitempty"`
	MaxLength int32 `json:"maxLength,omitempty"`
	Min float64 `json:"min,omitempty"`
	MinLength int32 `json:"minLength,omitempty"`
	Options []SchemaOption `json:"options,omitempty"`
	Pattern string `json:"pattern,omitempty"`
	Required bool `json:"required,omitempty"`
}
