/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1Manifest struct {
	Annotations   map[string]string `json:"annotations,omitempty"`
	Config        *V1Descriptor     `json:"config"`
	Layers        []V1Descriptor    `json:"layers"`
	MediaType     string            `json:"mediaType,omitempty"`
	SchemaVersion int64             `json:"schemaVersion"`
	Subject       *V1Descriptor     `json:"subject,omitempty"`
}
