/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1alpha1WorkflowStepStatus struct {
	FirstExecuteTime string `json:"firstExecuteTime,omitempty"`
	Id string `json:"id"`
	LastExecuteTime string `json:"lastExecuteTime,omitempty"`
	Message string `json:"message,omitempty"`
	Name string `json:"name,omitempty"`
	Phase string `json:"phase,omitempty"`
	Reason string `json:"reason,omitempty"`
	SubSteps []V1alpha1StepStatus `json:"subSteps,omitempty"`
	Type_ string `json:"type,omitempty"`
}
