/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1ManagedPluginDto struct {
	AuthSecret *TypesKubernetesSecret `json:"authSecret,omitempty"`
	AuthType string `json:"authType,omitempty"`
	Backend bool `json:"backend"`
	BackendService *TypesKubernetesService `json:"backendService"`
	BackendType string `json:"backendType"`
	BaseURL string `json:"baseURL"`
	Category string `json:"category"`
	Class string `json:"class"`
	DefaultNavURL string `json:"defaultNavURL"`
	Enabled bool `json:"enabled"`
	Id string `json:"id"`
	Includes []TypesIncludes `json:"includes"`
	Info *TypesInfo `json:"info"`
	JsonSetting *interface{} `json:"jsonSetting"`
	KubePermissions []V1PolicyRule `json:"kubePermissions,omitempty"`
	Module string `json:"module"`
	Name string `json:"name"`
	Proxy bool `json:"proxy"`
	Requirement *TypesRequirement `json:"requirement,omitempty"`
	Routes []TypesRoute `json:"routes,omitempty"`
	SecureJsonFields map[string]bool `json:"secureJsonFields"`
	SubType string `json:"subType"`
	Type_ string `json:"type"`
}
