/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1SystemInfoRequest struct {
	DexUserDefaultProjects []ModelProjectRef `json:"dexUserDefaultProjects,omitempty"`
	EnableCollection       bool              `json:"enableCollection"`
	LoginType              string            `json:"loginType"`
	VelaAddress            string            `json:"velaAddress,omitempty"`
}
