/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1ImageRegistry struct {
	Domain     string `json:"domain"`
	Name       string `json:"name"`
	SecretName string `json:"secretName"`
}
