/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CommonHttpOption struct {
	CaFile string `json:"caFile,omitempty"`
	CertFile string `json:"certFile,omitempty"`
	InsecureSkipTLS bool `json:"insecureSkipTLS,omitempty"`
	KeyFile string `json:"keyFile,omitempty"`
	Password string `json:"password,omitempty"`
	Username string `json:"username,omitempty"`
}
