/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1ApplicationDeployRequest struct {
	CodeInfo *ModelCodeInfo `json:"codeInfo,omitempty"`
	Force bool `json:"force"`
	ImageInfo *ModelImageInfo `json:"imageInfo,omitempty"`
	Note string `json:"note"`
	TriggerType string `json:"triggerType"`
	WorkflowName string `json:"workflowName"`
}
