/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CloudproviderCloudCluster struct {
	ApiServerURL string `json:"apiServerURL"`
	DashboardURL string `json:"dashboardURL"`
	Id string `json:"id"`
	Labels map[string]string `json:"labels"`
	Name string `json:"name"`
	Provider string `json:"provider"`
	RegionID string `json:"regionID"`
	Status string `json:"status"`
	Type_ string `json:"type"`
	VpcID string `json:"vpcID"`
	Zone string `json:"zone"`
	ZoneID string `json:"zoneID"`
}
