/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1CreateConfigDistributionRequest struct {
	Configs []V1NamespacedName `json:"configs"`
	Name    string             `json:"name"`
	Targets []V1ClusterTarget  `json:"targets"`
}
