/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

import (
	"time"
)

type V1RoleBase struct {
	Alias       string        `json:"alias,omitempty"`
	CreateTime  time.Time     `json:"createTime"`
	Name        string        `json:"name"`
	Permissions []V1NameAlias `json:"permissions"`
	UpdateTime  time.Time     `json:"updateTime"`
}
