/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

import (
	"time"
)

type V1WorkflowRecordBase struct {
	ApplicationRevision string    `json:"applicationRevision"`
	EndTime             time.Time `json:"endTime,omitempty"`
	Message             string    `json:"message"`
	Mode                string    `json:"mode"`
	Name                string    `json:"name"`
	Namespace           string    `json:"namespace"`
	StartTime           time.Time `json:"startTime,omitempty"`
	Status              string    `json:"status"`
	WorkflowAlias       string    `json:"workflowAlias"`
	WorkflowName        string    `json:"workflowName"`
}
