/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1alpha1WorkflowRunSpec struct {
	Context      string                       `json:"context,omitempty"`
	Mode         *V1alpha1WorkflowExecuteMode `json:"mode,omitempty"`
	WorkflowRef  string                       `json:"workflowRef,omitempty"`
	WorkflowSpec *V1alpha1WorkflowSpec        `json:"workflowSpec,omitempty"`
}
