/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1Config struct {
	ArgsEscaped     bool                            `json:"ArgsEscaped,omitempty"`
	AttachStderr    bool                            `json:"AttachStderr,omitempty"`
	AttachStdin     bool                            `json:"AttachStdin,omitempty"`
	AttachStdout    bool                            `json:"AttachStdout,omitempty"`
	Cmd             []string                        `json:"Cmd,omitempty"`
	Domainname      string                          `json:"Domainname,omitempty"`
	Entrypoint      []string                        `json:"Entrypoint,omitempty"`
	Env             []string                        `json:"Env,omitempty"`
	ExposedPorts    map[string]V1ConfigExposedPorts `json:"ExposedPorts,omitempty"`
	Healthcheck     *V1HealthConfig                 `json:"Healthcheck,omitempty"`
	Hostname        string                          `json:"Hostname,omitempty"`
	Image           string                          `json:"Image,omitempty"`
	Labels          map[string]string               `json:"Labels,omitempty"`
	MacAddress      string                          `json:"MacAddress,omitempty"`
	NetworkDisabled bool                            `json:"NetworkDisabled,omitempty"`
	OnBuild         []string                        `json:"OnBuild,omitempty"`
	OpenStdin       bool                            `json:"OpenStdin,omitempty"`
	Shell           []string                        `json:"Shell,omitempty"`
	StdinOnce       bool                            `json:"StdinOnce,omitempty"`
	StopSignal      string                          `json:"StopSignal,omitempty"`
	Tty             bool                            `json:"Tty,omitempty"`
	User            string                          `json:"User,omitempty"`
	Volumes         map[string]V1ConfigVolumes      `json:"Volumes,omitempty"`
	WorkingDir      string                          `json:"WorkingDir,omitempty"`
}
