/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type CommonApplicationComponent struct {
	DependsOn        []string                 `json:"dependsOn,omitempty"`
	ExternalRevision string                   `json:"externalRevision,omitempty"`
	Inputs           []V1alpha1InputItem      `json:"inputs,omitempty"`
	Name             string                   `json:"name"`
	Outputs          []V1alpha1OutputItem     `json:"outputs,omitempty"`
	Properties       string                   `json:"properties,omitempty"`
	Scopes           map[string]string        `json:"scopes,omitempty"`
	Traits           []CommonApplicationTrait `json:"traits,omitempty"`
	Type_            string                   `json:"type"`
}
