/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type CommonAppStatus struct {
	AppliedResources   []CommonClusterObjectReference     `json:"appliedResources,omitempty"`
	Components         []V1ObjectReference                `json:"components,omitempty"`
	Conditions         []ConditionCondition               `json:"conditions,omitempty"`
	LatestRevision     *CommonRevision                    `json:"latestRevision,omitempty"`
	ObservedGeneration int64                              `json:"observedGeneration,omitempty"`
	Policy             []CommonPolicyStatus               `json:"policy,omitempty"`
	Services           []CommonApplicationComponentStatus `json:"services,omitempty"`
	Status             string                             `json:"status,omitempty"`
	Workflow           *CommonWorkflowStatus              `json:"workflow,omitempty"`
}
