/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

import (
	"time"
)

type V1Env struct {
	Alias       string        `json:"alias"`
	CreateTime  time.Time     `json:"createTime"`
	Description string        `json:"description,omitempty"`
	Name        string        `json:"name"`
	Namespace   string        `json:"namespace"`
	Project     *V1NameAlias  `json:"project"`
	Targets     []V1NameAlias `json:"targets,omitempty"`
	UpdateTime  time.Time     `json:"updateTime"`
}
