/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type ConfigClusterTargetStatus struct {
	Application *ConfigNamespacedName `json:"application"`
	ClusterName string                `json:"clusterName"`
	Message     string                `json:"message"`
	Namespace   string                `json:"namespace"`
	Status      string                `json:"status"`
}
