/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

import (
	"time"
)

type V1DetailWorkflowRecordResponse struct {
	ApplicationRevision string                    `json:"applicationRevision"`
	DeployTime          time.Time                 `json:"deployTime"`
	DeployUser          string                    `json:"deployUser"`
	EndTime             time.Time                 `json:"endTime,omitempty"`
	Message             string                    `json:"message"`
	Mode                string                    `json:"mode"`
	Name                string                    `json:"name"`
	Namespace           string                    `json:"namespace"`
	Note                string                    `json:"note"`
	StartTime           time.Time                 `json:"startTime,omitempty"`
	Status              string                    `json:"status"`
	Steps               []ModelWorkflowStepStatus `json:"steps,omitempty"`
	TriggerType         string                    `json:"triggerType"`
	WorkflowAlias       string                    `json:"workflowAlias"`
	WorkflowName        string                    `json:"workflowName"`
}
