/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type ModelWorkflowStep struct {
	Alias       string                    `json:"alias"`
	DependsOn   []string                  `json:"dependsOn"`
	Description string                    `json:"description"`
	If_         string                    `json:"if,omitempty"`
	Inputs      []V1alpha1InputItem       `json:"inputs,omitempty"`
	Meta        *V1alpha1WorkflowStepMeta `json:"meta,omitempty"`
	Mode        string                    `json:"mode,omitempty"`
	Name        string                    `json:"name"`
	OrderIndex  int32                     `json:"orderIndex"`
	Outputs     []V1alpha1OutputItem      `json:"outputs,omitempty"`
	Properties  map[string]interface{}    `json:"properties,omitempty"`
	SubSteps    []ModelWorkflowStepBase   `json:"subSteps,omitempty"`
	Timeout     string                    `json:"timeout,omitempty"`
	Type_       string                    `json:"type"`
}
