/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModelImageInfo struct {
	Repository *ModelImageRepository `json:"repository,omitempty"`
	Resource *ModelImageResource `json:"resource,omitempty"`
	Type_ string `json:"type"`
}
