/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type V1ProjectBase struct {
	Alias string `json:"alias"`
	CreateTime time.Time `json:"createTime"`
	Description string `json:"description"`
	Name string `json:"name"`
	Namespace string `json:"namespace"`
	Owner *V1NameAlias `json:"owner,omitempty"`
	UpdateTime time.Time `json:"updateTime"`
}
