/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1EnableAddonRequest struct {
	Args *interface{} `json:"args,omitempty"`
	Clusters []string `json:"clusters,omitempty"`
	RegistryName string `json:"registryName,omitempty"`
	Version string `json:"version,omitempty"`
}
