/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

import (
	"time"
)

type ModelApplicationComponent struct {
	Alias            string                        `json:"alias"`
	AppPrimaryKey    string                        `json:"appPrimaryKey"`
	CreateTime       time.Time                     `json:"createTime"`
	Creator          string                        `json:"creator"`
	DependsOn        []string                      `json:"dependsOn,omitempty"`
	Description      string                        `json:"description,omitempty"`
	ExternalRevision string                        `json:"externalRevision,omitempty"`
	Icon             string                        `json:"icon,omitempty"`
	Inputs           []V1alpha1InputItem           `json:"inputs,omitempty"`
	Labels           map[string]string             `json:"labels,omitempty"`
	Main             bool                          `json:"main"`
	Name             string                        `json:"name"`
	Outputs          []V1alpha1OutputItem          `json:"outputs,omitempty"`
	Properties       *ModelJsonStruct              `json:"properties,omitempty"`
	Scopes           map[string]string             `json:"scopes,omitempty"`
	Traits           []ModelApplicationTrait       `json:"traits,omitempty"`
	Type_            string                        `json:"type"`
	UpdateTime       time.Time                     `json:"updateTime"`
	WorkloadType     *CommonWorkloadTypeDescriptor `json:"workloadType,omitempty"`
}
