/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1UpdatePolicyRequest struct {
	Alias              string                    `json:"alias"`
	Description        string                    `json:"description"`
	EnvName            string                    `json:"envName"`
	Properties         string                    `json:"properties"`
	Type_              string                    `json:"type"`
	WorkflowPolicyBind []V1WorkflowPolicyBinding `json:"workflowPolicyBind"`
}
