/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1Platform struct {
	Architecture string `json:"architecture"`
	Features []string `json:"features,omitempty"`
	Os string `json:"os"`
	OsFeatures []string `json:"os.features,omitempty"`
	OsVersion string `json:"os.version,omitempty"`
	Variant string `json:"variant,omitempty"`
}
