/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

import (
	"time"
)

type V1ComponentBase struct {
	Alias         string                        `json:"alias"`
	ComponentType string                        `json:"componentType"`
	CreateTime    time.Time                     `json:"createTime"`
	Creator       string                        `json:"creator,omitempty"`
	DependsOn     []string                      `json:"dependsOn"`
	Description   string                        `json:"description"`
	Icon          string                        `json:"icon,omitempty"`
	Inputs        []V1alpha1InputItem           `json:"inputs,omitempty"`
	Labels        map[string]string             `json:"labels,omitempty"`
	Main          bool                          `json:"main"`
	Name          string                        `json:"name"`
	Outputs       []V1alpha1OutputItem          `json:"outputs,omitempty"`
	Traits        []V1ApplicationTrait          `json:"traits"`
	UpdateTime    time.Time                     `json:"updateTime"`
	WorkloadType  *CommonWorkloadTypeDescriptor `json:"workloadType,omitempty"`
}
