/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type CommonRevision struct {
	Name         string `json:"name"`
	Revision     int64  `json:"revision"`
	RevisionHash string `json:"revisionHash,omitempty"`
}
