/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1ListProjectUsersResponse struct {
	Total int64 `json:"total"`
	Users []V1ProjectUserBase `json:"users"`
}
