/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type CommonChildResourceKind struct {
	ApiVersion string            `json:"apiVersion"`
	Kind       string            `json:"kind"`
	Selector   map[string]string `json:"selector,omitempty"`
}
