/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SchemaUiParameter struct {
	Additional bool `json:"additional,omitempty"`
	AdditionalParameter *SchemaUiParameter `json:"additionalParameter,omitempty"`
	Conditions []SchemaCondition `json:"conditions,omitempty"`
	Description string `json:"description"`
	Disable bool `json:"disable,omitempty"`
	JsonKey string `json:"jsonKey"`
	Label string `json:"label"`
	Sort int32 `json:"sort"`
	Style *SchemaStyle `json:"style,omitempty"`
	SubParameterGroupOption []SchemaGroupOption `json:"subParameterGroupOption,omitempty"`
	SubParameters []SchemaUiParameter `json:"subParameters,omitempty"`
	UiType string `json:"uiType"`
	Validate *SchemaValidate `json:"validate,omitempty"`
}
