/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type ChartMaintainer struct {
	Email string `json:"email,omitempty"`
	Name  string `json:"name,omitempty"`
	Url   string `json:"url,omitempty"`
}
