/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1HealthConfig struct {
	Interval    int64    `json:"Interval,omitempty"`
	Retries     int32    `json:"Retries,omitempty"`
	StartPeriod int64    `json:"StartPeriod,omitempty"`
	Test        []string `json:"Test,omitempty"`
	Timeout     int64    `json:"Timeout,omitempty"`
}
