/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1alpha1InputItem struct {
	From         string `json:"from"`
	ParameterKey string `json:"parameterKey,omitempty"`
}
