/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1InstallPluginRequest struct {
	Disable bool `json:"disable,omitempty"`
	Options *CommonHttpOption `json:"options,omitempty"`
	Url string `json:"url"`
}
