/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type AddonGitlabAddonSource struct {
	Path  string `json:"path,omitempty"`
	Repo  string `json:"repo,omitempty"`
	Token string `json:"token,omitempty"`
	Url   string `json:"url,omitempty"`
}
