/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1CreateApplicationRequest struct {
	Alias       string                    `json:"alias,omitempty"`
	Component   *V1CreateComponentRequest `json:"component"`
	Description string                    `json:"description,omitempty"`
	EnvBinding  []V1EnvBinding            `json:"envBinding,omitempty"`
	Icon        string                    `json:"icon"`
	Labels      map[string]string         `json:"labels,omitempty"`
	Name        string                    `json:"name"`
	Project     string                    `json:"project"`
}
