/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type V1DetailRevisionResponse struct {
	AppPrimaryKey string `json:"appPrimaryKey"`
	ApplyAppConfig string `json:"applyAppConfig,omitempty"`
	CodeInfo *ModelCodeInfo `json:"codeInfo,omitempty"`
	CreateTime time.Time `json:"createTime"`
	DeployUser *V1NameAlias `json:"deployUser"`
	EnvName string `json:"envName"`
	ImageInfo *ModelImageInfo `json:"imageInfo,omitempty"`
	Note string `json:"note"`
	Reason string `json:"reason"`
	RevisionCRName string `json:"revisionCRName"`
	RollbackVersion string `json:"rollbackVersion,omitempty"`
	Status string `json:"status"`
	TriggerType string `json:"triggerType"`
	UpdateTime time.Time `json:"updateTime"`
	Version string `json:"version"`
	WorkflowName string `json:"workflowName"`
}
