/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1beta1WorkflowStepDefinitionSpec struct {
	DefinitionRef *CommonDefinitionReference `json:"definitionRef,omitempty"`
	Schematic     *CommonSchematic           `json:"schematic,omitempty"`
}
