/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AddonHelmSource struct {
	InsecureSkipTLS bool `json:"insecureSkipTLS,omitempty"`
	Password string `json:"password,omitempty"`
	Url string `json:"url,omitempty"`
	Username string `json:"username,omitempty"`
}
