/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1ConfigFile struct {
	Architecture string `json:"architecture"`
	Author string `json:"author,omitempty"`
	Config *V1Config `json:"config"`
	Container string `json:"container,omitempty"`
	Created string `json:"created,omitempty"`
	DockerVersion string `json:"docker_version,omitempty"`
	History []V1History `json:"history,omitempty"`
	Os string `json:"os"`
	OsFeatures []string `json:"os.features,omitempty"`
	OsVersion string `json:"os.version,omitempty"`
	Rootfs *V1RootFs `json:"rootfs"`
	Variant string `json:"variant,omitempty"`
}
