/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1ApplicationRequest struct {
	Components []CommonApplicationComponent `json:"components"`
	Policies   []V1beta1AppPolicy           `json:"policies,omitempty"`
	Workflow   *V1beta1Workflow             `json:"workflow,omitempty"`
}
