/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1ListContextValueResponse struct {
	Contexts map[string][]ModelValue `json:"contexts"`
	Total    int32                   `json:"total"`
}
