/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1EnvBindingTarget struct {
	Alias   string           `json:"alias"`
	Cluster *V1ClusterTarget `json:"cluster,omitempty"`
	Name    string           `json:"name"`
}
