/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1ImageInfo struct {
	Info        *V1ConfigFile `json:"info,omitempty"`
	Manifest    *V1Manifest   `json:"manifest"`
	Message     string        `json:"message,omitempty"`
	Name        string        `json:"name"`
	Registry    string        `json:"registry"`
	SecretNames []string      `json:"secretNames"`
	Size        int64         `json:"size"`
}
