/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type V1ApplicationDeployResponse struct {
	CodeInfo *ModelCodeInfo `json:"codeInfo,omitempty"`
	CreateTime time.Time `json:"createTime"`
	DeployUser *V1NameAlias `json:"deployUser,omitempty"`
	EnvName string `json:"envName"`
	ImageInfo *ModelImageInfo `json:"imageInfo,omitempty"`
	Note string `json:"note"`
	Reason string `json:"reason,omitempty"`
	Record *V1WorkflowRecordBase `json:"record"`
	Status string `json:"status"`
	TriggerType string `json:"triggerType"`
	Version string `json:"version"`
	WorkflowName string `json:"workflowName"`
}
