/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type ChartDependency struct {
	Alias        string                        `json:"alias,omitempty"`
	Condition    string                        `json:"condition,omitempty"`
	Enabled      bool                          `json:"enabled,omitempty"`
	ImportValues []ChartDependencyImportValues `json:"import-values,omitempty"`
	Name         string                        `json:"name"`
	Repository   string                        `json:"repository"`
	Tags         []string                      `json:"tags,omitempty"`
	Version      string                        `json:"version,omitempty"`
}
