/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * API version: v1beta1
 * Contact: feedback@mail.kubevela.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package velaclient

type V1beta1AppPolicy struct {
	Name       string `json:"name,omitempty"`
	Properties string `json:"properties,omitempty"`
	Type_      string `json:"type"`
}
